"""create users and trips tables

Revision ID: 4c77ed13e02a
Revises: 
Create Date: 2026-09-06 15:56:40.601667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c77ed13e02a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('trips', 'interests',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False,postgresql_using='interests::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'interests',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,postgresql_using='interests::json')
    op.alter_column('trips', 'budget',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
